// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57tS6PuN3oqfO0gQwKyf-Gjg8vYk48hg',
    appId: '1:405887286047:web:14a9f773ac15afb2518e2a',
    messagingSenderId: '405887286047',
    projectId: 'tutorbase-336701',
    authDomain: 'tutorbase-336701.firebaseapp.com',
    storageBucket: 'tutorbase-336701.appspot.com',
    measurementId: 'G-8BHE79ZP84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvdKle8uMAdE_vpbnvield6LEQq48ovpw',
    appId: '1:405887286047:android:c18c5f2fb1e545ab518e2a',
    messagingSenderId: '405887286047',
    projectId: 'tutorbase-336701',
    storageBucket: 'tutorbase-336701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1eY2Dmn5DKbry-kvdtmhT4P5W9muKGj4',
    appId: '1:405887286047:ios:ad43aac318304565518e2a',
    messagingSenderId: '405887286047',
    projectId: 'tutorbase-336701',
    storageBucket: 'tutorbase-336701.appspot.com',
    androidClientId:
        '405887286047-eaq955f38tvb98matddtot0ehrvsnbgf.apps.googleusercontent.com',
    iosClientId:
        '405887286047-l8ql7eq7apveh78a7qpn0kkui61kbbpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuiiPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1eY2Dmn5DKbry-kvdtmhT4P5W9muKGj4',
    appId: '1:405887286047:ios:ad43aac318304565518e2a',
    messagingSenderId: '405887286047',
    projectId: 'tutorbase-336701',
    storageBucket: 'tutorbase-336701.appspot.com',
    androidClientId:
        '405887286047-eaq955f38tvb98matddtot0ehrvsnbgf.apps.googleusercontent.com',
    iosClientId:
        '405887286047-l8ql7eq7apveh78a7qpn0kkui61kbbpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuiiPoc',
  );
}
