// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM7Z01N0DZ5h4N4K4ve3E4DndXB1uS9lM',
    appId: '1:411012467075:web:dff70699f1dc23853a4eb6',
    messagingSenderId: '411012467075',
    projectId: 'tuii-380018',
    authDomain: 'tuii-380018.firebaseapp.com',
    storageBucket: 'tuii-380018.appspot.com',
    measurementId: 'G-YN4KNQXSYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpvXJoLieqlWoun5_lso14RRqx85I7pAM',
    appId: '1:411012467075:android:842175fee2a98bbb3a4eb6',
    messagingSenderId: '411012467075',
    projectId: 'tuii-380018',
    storageBucket: 'tuii-380018.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwyf__9QldCUTW-UxHf2KkXoUisjbsbi0',
    appId: '1:411012467075:ios:9086d6e175a1bb3c3a4eb6',
    messagingSenderId: '411012467075',
    projectId: 'tuii-380018',
    storageBucket: 'tuii-380018.appspot.com',
    iosClientId: '411012467075-rucm61fo75be13sqeufa4ggj3r38oec2.apps.googleusercontent.com',
    iosBundleId: 'io.tui.poc.tuiiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwyf__9QldCUTW-UxHf2KkXoUisjbsbi0',
    appId: '1:411012467075:ios:c859c87e84c744373a4eb6',
    messagingSenderId: '411012467075',
    projectId: 'tuii-380018',
    storageBucket: 'tuii-380018.appspot.com',
    iosClientId: '411012467075-qjult3p7r1a9vp5l34qbl9b5abk52a0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuiiPoc',
  );
}
